name: carolexample
on:
  schedule:
    - cron: '*/5 * * * *' # Every 5 minutes
jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check Tickets
        uses: Ctang1001/melon-ticket-actions@v1.0.0
        with:
          product-id: 204755
          schedule-id: 100001
          seat-id: 1_0
          slack-incoming-webhook-url: https://hooks.slack.com/services/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
          message: '<@U4CF18RKL> 티켓사세요'
