name: workflow
on: push
jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v1
      - name: Prepare
        run: npm ci
      - name: Lint
        uses: Ctang1001/tslint-actions@master
        with:
          token: e3de29582fb2670e8f66eda1e02d2db15a5002ed
          pattern: '*.ts'
      - name: Build
        run: npm run build
      - name: Publish
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: npx semantic-release
        env:
          GH_TOKEN: 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
